apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdicidr
  namespace: production
  labels:
    app: rdicidr
spec:
  # obrigatório para StatefulSet
  serviceName: rdicidr-headless
  replicas: 3
  selector:
    matchLabels:
      app: rdicidr
  template:
    metadata:
      labels:
        app: rdicidr
    spec:
      containers:
        - name: web
          image: rdicidr:0.1.0        # imagem que tu vai buildar do teu app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets   # Secret definido em secret.yml
                  key: MY_SECRET
          readinessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
