apiVersion: v1
kind: Service
metadata:
  name: rdicidr-headless
  namespace: production
spec:
  clusterIP: None
  selector:
    app: rdicidr
  ports:
    - port: 8080
      targetPort: 8080
      name: web
---
apiVersion: v1
kind: Service
metadata:
  name: rdicidr-svc
  namespace: production
spec:
  selector:
    app: rdicidr
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
